reports/urls.py
from reports import views
from django.conf.urls import url

app_name='reports'
urlpatterns = [
    url(r'^create_sales_reports/$', views.create_sales_reports,name='create_sales_reports'),
    url(r'^create_monthly_reports/$', views.create_monthly_reports,name='create_monthly_reports'),
    url(r'^view_sales_reports/$', views.view_sales_reports,name='view_sales_reports'),
    url(r'^create_gst_reports/$', views.create_gst_reports,name='create_gst_reports'),
    url(r'^view_monthly_sales_reports/$', views.view_monthly_sales_reports,name='view_monthly_sales_reports'),
]

sales/urls.py
from sales import views
from django.conf.urls import url

app_name='sales'
urlpatterns = [
    url(r'^sales/$', views.sales_details,name='sales_details'),
    url(r'^sales_wholesale/$', views.sales_details_wholesale,name='sales_details_wholesale'),
    url(r'^dashboard_sales/$', views.dashboard_sales,name='dashboard_sales'),
   
    url(r'^stock_movement/$', views.stock_movement,name='stock_movement'),
    url(r'^create_sales/$', views.create_sales,name='create_sales'),
    url(r'^creating_sales/$', views.creating_sales,name='creating_sales'),
   
    url(r'^create_sales_ajax/$', views.create_sales_ajax,name='create_sales_ajax'),
    url(r'^sales/print_sales/(?P<id>\d+)$', views.print_sales,name='print_sales'),
    url(r'^sales/print_sales_wholesale/(?P<id>\d+)$', views.print_sales_wholesale,name='print_sales'),
    url(r'^sales/view_sales/(?P<id>\d+)$', views.view_sales,name='view_sales'),
   
    url(r'^sales/edit_sales/(?P<id>\d+)$', views.edit_sales,name='edit_sales'),
    url(r'^sales/update_sales/(?P<id>\d+)$', views.update_sales,name='update_sales'),
    url(r'^sales/delete_sales/(?P<id>\d+)$', views.delete_sales,name='delete_sales'),
    url(r'^sales/delete_all_sales/$', views.delete_all_sales,name='delete_all_sales'),
    url(r'^sales/delete_wholesale_sales/(?P<id>\d+)$', views.delete_wholesale_sales,name='delete_wholesale_sales'),
    url(r'^sales/delete_all_wholesale_sales/$', views.delete_all_wholesale_sales,name='delete_all_wholesale_sales'),
    url(r'^sales_dashboard_ajax/$', views.sales_dashboard_ajax,name='sales_dashboard_ajax'),
    
]

store_billing_lite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('dashboard.urls')),
    url(r'',include('product.urls')),
    url(r'',include('returns.urls')),
    url(r'',include('reports.urls')),
    url(r'',include('sales.urls')),
    url(r'',include('settings_billing.urls')),

]

reports/models.py
from django.db import models
import datetime
from datetime import datetime
from datetime import date
from django.utils import timezone
 

category_type= (
            ('Cash','Cash'),
            ('Bank','Bank')
            )
# Create your models here.
class create_sales_report_table(models.Model):
	create_sales_report_month_and_year=models.DateTimeField(default=datetime.now(),blank=True)
	create_sales_report_category=models.CharField(choices=category_type,max_length=10)






class create_Gst_report_table(models.Model):
	create_gst_report_month_and_year=models.DateTimeField(default=datetime.now(),blank=True)
	create_gst_report_category=models.CharField(choices=category_type,max_length=10)

reports/forms.py
from django import forms
month=(
	('1','January'),
	('2','February'),
	('3','March'),
	('4','April'),
	('5','May'),
	('6','June'),
	('7','July'),
	('8','August'),
	('9','September'),
	('10','October'),
	('11','November'),
	('12','December')
	)
category=(
	('all','all'),
	('b2b','B TO B'),
	('b2c','B TO C'),
	)



class create_sales_report(forms.Form):
	# create_sales_report_month=forms.ChoiceField(choices=month,widget=forms.Select(attrs={'class':'form-control',}))
	create_sales_report_year=forms.CharField (widget=forms.NumberInput(attrs={'class':'form-control','type':'number'}))
	create_sales_report_category=forms.ChoiceField(choices=category,widget=forms.Select(attrs={'class':'form-control',}))



class create_gst_report(forms.Form):
	create_gst_report_month_and_year=forms.DateField (widget=forms.DateInput(attrs={'class':'form-control','type':'date','id':'example-date-input'}))
	create_gst_report_category=forms.ChoiceField(choices=category,widget=forms.Select(attrs={'class':'form-control',}))

reports/views.py
from django.shortcuts import render
from reports.forms import create_sales_report,create_gst_report
from reports.models import create_sales_report_table,create_Gst_report_table

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from settings_billing.models import store_details
from django.http import HttpResponse
from product.models import products,categorisation,alternate_units
from sales.models import create_sales_table,create_sales_final,sale_totals,taxes,reports
import pandas as pd
# Create your views here.

@login_required(login_url='/login')
def create_sales_reports(request):
	
	form=create_sales_report()
	active_sidebar6=1
	return render(request,'reports/create_sales_reports.html',{'active_sidebar6':active_sidebar6,'form':form})

def create_monthly_reports(request):
	
	form=create_sales_report()
	active_sidebar6=1
	return render(request,'reports/create_monthly_report.html',{'active_sidebar6':active_sidebar6,'form':form})

#DAILY SALES
@login_required(login_url='/login')
def view_sales_reports(request):
	final_price=[]
	sale_date=[]
	sale_total=[]
	get_price=[]
	
	get_unit=[]
	spe_disc=[]
	payment_recieved=[]
	taxu=[]
	total_balance=0
	count=0
	df_tax_per=[]
	df_tax_gst=[]
	df_tax_total=[]

	if request.method == 'POST':
			
		form=create_sales_report(request.POST)
		if form.is_valid():
			
				
				
			create_sales_report_month=int(request.POST.get('create_sales_report_month'))
			create_sales_report_year=int(request.POST.get('create_sales_report_year'))
			sales=create_sales_final.objects.filter(sales_date__year=create_sales_report_year, sales_date__month=create_sales_report_month)
			daily_repor=reports.objects.all()
			
			for invo in sales:
				sale_date.append(invo.sales_date)
				sale_total.append(float(invo.sales_total))
				spe_disc.append(float(invo.sales_special_discount))
				payment_recieved.append(float(invo.sales_payment_received))
				total_balance=sum(sale_total)-sum(payment_recieved)
				sales_pro=create_sales_table.objects.filter(sales_invoice_no=invo.sale_invoice_ref)
				sales_prod=create_sales_table.objects.all()
				product_det=products.objects.all()
				
				count=count+1



			tax=taxes.objects.filter(sale_date__year=create_sales_report_year, sale_date__month=create_sales_report_month)
			for x in tax:
				df_tax_per.append(x.tax_percent)
				df_tax_gst.append(round(float(x.total_tax_amount)/2,2))
				df_tax_total.append(x.total_tax_amount)
			df=pd.DataFrame(list(zip(df_tax_per,df_tax_gst,df_tax_total)),columns=['a','b','c'])
			df_1=df.groupby('a', as_index=False).agg({'b':'sum', 'c':'sum'})

			listss=df_1.values.tolist()
			for tt in tax:
				taxu.append(float(tt.total_tax_amount))
				tota_tax=sum(taxu)
				tota_tax_rounded=round(tota_tax,2)
			# else: 
			# 	return HttpResponse(form.errors)
	store_info=store_details.objects.latest('id')
	form=create_sales_report()
	active_sidebar1=7
	return render(request,'reports/repo.html',{'active_sidebar1':active_sidebar1,'form':form,'sales':sales,'daily_repor':daily_repor,'sales_prod':sales_prod,'product_det':product_det,
			'count':count,'sales_totals':sum(sale_total),'spe_disc':sum(spe_disc),'payment_recieved':sum(payment_recieved),'total_balance':total_balance,
			'tota_tax':tota_tax_rounded,'tax':listss,'store_info':store_info})
	
#MONTHLY SALES
def view_monthly_sales_reports(request):
	
	
	taxu=[]
	totu=[]
	dates=[]
	counting=[]
	days=[]
	taxu=[]
	pri_taxu=[]
	tota_tax=[]
	sale_date=[]
	sale_total=[]
	spe_disc=[]
	payment_recieved=[]
	sale_total1=[]
	sum_tax=0
	df_tax_per=[]
	df_tax_gst=[]
	df_tax_total=[]
	if request.method == 'POST':
			
		form=create_sales_report(request.POST)
		if form.is_valid():
			
				
				
			create_sales_report_month=int(request.POST.get('create_sales_report_month'))
			create_sales_report_year=int(request.POST.get('create_sales_report_year'))
			sales=create_sales_final.objects.filter(sales_date__year=create_sales_report_year, sales_date__month=create_sales_report_month)
			for invo in sales:
				sale_date.append(invo.sales_date)
				sale_total.append(float(invo.sales_total))
				sale_total1.append(float(invo.sales_total))
				spe_disc.append(float(invo.sales_special_discount))
				payment_recieved.append(float(invo.sales_payment_received))
				total_balance=sum(sale_total)-sum(payment_recieved)
				sales_pro=create_sales_table.objects.filter(sales_invoice_no=invo.sale_invoice_ref)
				sales_prod=create_sales_table.objects.all()
				product_det=products.objects.all()

			
				
			taxe=taxes.objects.filter(sale_date__year=create_sales_report_year, sale_date__month=create_sales_report_month)
			for x in taxe:
				df_tax_per.append(x.tax_percent)
				df_tax_gst.append(round(float(x.total_tax_amount)/2,2))
				df_tax_total.append(x.total_tax_amount)
			df=pd.DataFrame(list(zip(df_tax_per,df_tax_gst,df_tax_total)),columns=['a','b','c'])
			df_1=df.groupby('a', as_index=False).agg({'b':'sum', 'c':'sum'})

			listss=df_1.values.tolist()
			
			for tt in taxe:
				taxu.append(float(tt.total_tax_amount))
				tota_tax=sum(taxu)
				tota_tax=round(tota_tax,2)
			for tp in taxe:
				pri_taxu.append(float(tp.price_tax_amount))
				tota_pri_tax=sum(pri_taxu)
				tota_pri_tax=round(tota_pri_tax,2)
			for da in taxe:
				day_date=da.sale_date
				days.append(day_date.day)
			days = list(dict.fromkeys(days))
			
			for tota in days:
				total=0
				total_ta=0

				tax=taxes.objects.filter(sale_date__year=create_sales_report_year, sale_date__month=create_sales_report_month,sale_date__day=tota)
				
				for tta in tax:
					total=float(total)+float(tta.total_tax_amount)
					total_ta=float(total_ta)+float(tta.price_tax_amount)
				dates.append(tta.sale_date)	
				
				taxu.append(total)
				pri_taxu.append(total_ta)
				sale_total=0	
				tot=sale_totals.objects.filter(sales_date__year=create_sales_report_year, sales_date__month=create_sales_report_month,sales_date__day=tota)
				
				for tott in tot:
					sale_total=float(sale_total)+float(tott.sales_totals)
					
					sale_total=round(sale_total,2)
				
				totu.append(sale_total)
				salee=create_sales_final.objects.filter(sales_date__year=create_sales_report_year, sales_date__month=create_sales_report_month,sales_date__day=tota)
				count=0
				for cc in salee:
					count=count+1
				counting.append(count)
		zipped2=zip(dates,counting,taxu,pri_taxu,totu)
		zipped=zip(dates,counting,taxu,pri_taxu,totu)
		# for tui in pri_taxu:

		# 	sum_tax=float(sum_tax)+float(tui)
		for g,h,i,j,k in zipped2:
			sum_tax=float(sum_tax)+float(j)
		

		single_tax=taxes.objects.all()		
			

			# else:
			# 	return HttpResponse(form.errors)
	store_info=store_details.objects.latest('id')
	form=create_sales_report()
	active_sidebar1=7

	return render(request,'reports/monthlyrepo.html',{'active_sidebar1':active_sidebar1,'form':form,'sales':sales,'zipped':zipped,'single_tax':single_tax,'taxe':listss,'tota_tax':tota_tax,'tota_pri_tax':tota_pri_tax,'count':count,\
		'spe_disc':sum(spe_disc),'payment_recieved':sum(payment_recieved),'total_balance':total_balance,'sales_totals':sum(sale_total1),'total_payable_tax':sum_tax,'store_info':store_info})
	

@login_required(login_url='/login')
def create_gst_reports(request):
	if request.method == 'POST':
		
		form=create_gst_report(request.POST)
		if form.is_valid():
			cre_gst_rpt=create_Gst_report_table(
				create_gst_report_month_and_year=form.cleaned_data['create_gst_report_month_and_year'],
				create_gst_report_category=form.cleaned_data['create_gst_report_category'],
				)
			cre_gst_rpt.save()
		else:
			return HttpResponse(form.errors)

	form=create_gst_report()
	active_sidebar2=7
	return render(request,'reports/create_gst_reports.html',{'active_sidebar2':active_sidebar2,'form':form})

reports/templates/reports/create_monthly_report.html
{%extends 'dashboard/layout.html'%}
{% load static %}
{% load mathfilters %}
{%block content%}





<div class="content-wrapper">
<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">CREATE MONTHLY REPORT</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>

<section class="content">			


<div class="row">
		  
		<div class="col-12">
         
         
            <!-- /.box-header -->
            <div class="row">			  
		<div class="col-lg-4 col-12">
			  <div class="box">
				<div class="box-header with-border">
				  <h4 class="box-title">Create Monthly Report</h4>			
					<ul class="box-controls pull-right">
					 <form class="form" method="post" action="{% url 'reports:view_monthly_sales_reports'%}">
         	{% csrf_token %}
					  <li><a class="box-btn-slide" href="#"></a></li>	
					  
					</ul>
				</div>
				<!-- /.box-header -->
				<form class="form">
					<div class="box-body">
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Month</label>
							 <!-- {{form.create_sales_report_month}} -->
							 <select name="create_sales_report_month" class="form-control" id="month">
							 	<option value="1">January</option>
							 	<option value="2">February</option>
							 	<option value="3">March</option>
							 	<option value="4">April</option>
							 	<option value="5">May</option>
							 	<option value="6">June</option>
							 	<option value="7">July</option>
							 	<option value="8">August</option>
							 	<option value="9">September</option>
							 	<option value="10">October</option>
							 	<option value="11">November</option>
							 	<option value="12">December</option>
							 	
							 </select>
							</div>
						  </div>
						</div>

						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Year</label>
							 <input type="number" name="create_sales_report_year" class="form-control" id="year">
							</div>
						  </div>
						</div>
					
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label> Category</label>
							  <select name="create_sales_report_category" class="form-control">
							 	<option value="all">all</option>
							 	<option value="b2b">B TO B</option>
							 	<option value="b2c">B TO C</option>
							 </select>
							</div>
						  </div>
						 
						</div>
						
						
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group ">
							</div>
						</div>				
			</div>
		 <input type="submit" class="btn btn-success" value="Submit">
					<!-- /.box-body -->
					</div> 

                </form>
			  </div>
			  

			  <!-- /.box -->			
		</div>  

		  
		
		</div>  
			  <!-- /.box -->			
		</div>
				</div>
            </div>
            <!-- /.box-body -->
         


 <script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script>         

<script type="text/javascript">
	$(document).ready(function(){

var today=new Date();


$('#year').val(today.getFullYear()); 


var d = new Date();
  var n = d.getMonth();
$('#month').val(n+1); 

 })
</script>




   {%endblock%}	

reports/templates/reports/create_sales_reports.html
{%extends 'dashboard/layout.html'%}
{% load static %}

{%block content%}





<div class="content-wrapper">
<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">CREATE DAILY SALES REPORT</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>

<section class="content">	

<div class="row">
		  
		<div class="col-12">
         
         
            <!-- /.box-header -->
            <div class="row">			  
		<div class="col-lg-4 col-12">
			  <div class="box">
				<div class="box-header with-border">
				  <h4 class="box-title">Create Sales Report</h4>			
					<ul class="box-controls pull-right">
					 <form class="form" method="post" action="{% url 'reports:view_sales_reports'%}">
         	{% csrf_token %}
					  <li><a class="box-btn-slide" href="#"></a></li>	
					  
					</ul>
				</div>
				<!-- /.box-header -->
				<form class="form">
					<div class="box-body">
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Month</label>
							 <!-- {{form.create_sales_report_month}} -->
							 <select name="create_sales_report_month" class="form-control" id="month">
							 	<option value="1">January</option>
							 	<option value="2">February</option>
							 	<option value="3">March</option>
							 	<option value="4">April</option>
							 	<option value="5">May</option>
							 	<option value="6">June</option>
							 	<option value="7">July</option>
							 	<option value="8">August</option>
							 	<option value="9">September</option>
							 	<option value="10">October</option>
							 	<option value="11">November</option>
							 	<option value="12">December</option>
							 	
							 </select>
							</div>
						  </div>
						</div>

						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Year</label>
							 <input type="number" name="create_sales_report_year" class="form-control" id="year">
							</div>
						  </div>
						</div>
					
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label> Category</label>
							  <select name="create_sales_report_category" class="form-control">
							 	<option value="all">all</option>
							 	<option value="b2b">B TO B</option>
							 	<option value="b2c">B TO C</option>
							 </select>
							</div>
						  </div>
						 
						</div>
						
						
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group ">
							</div>
						</div>				
			</div>
		 <input type="submit" class="btn btn-success" value="Submit">
					<!-- /.box-body -->
					</div> 

                </form>
			  </div>
			  

			  <!-- /.box -->			
		</div>  

		  
		
		</div>  
			  <!-- /.box -->			
		</div>
				</div>
            </div>
            <!-- /.box-body -->


 <script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script>         

<script type="text/javascript">
	$(document).ready(function(){

var today=new Date();


$('#year').val(today.getFullYear()); 


var d = new Date();
  var n = d.getMonth();
$('#month').val(n+1); 

 })
</script>




   {%endblock%}	