sales/urls.py
from sales import views
from django.conf.urls import url

app_name='sales'
urlpatterns = [
    url(r'^sales/$', views.sales_details,name='sales_details'),
    url(r'^sales_wholesale/$', views.sales_details_wholesale,name='sales_details_wholesale'),
    url(r'^dashboard_sales/$', views.dashboard_sales,name='dashboard_sales'),
   
    url(r'^stock_movement/$', views.stock_movement,name='stock_movement'),
    url(r'^create_sales/$', views.create_sales,name='create_sales'),
    url(r'^creating_sales/$', views.creating_sales,name='creating_sales'),
   
    url(r'^create_sales_ajax/$', views.create_sales_ajax,name='create_sales_ajax'),
    url(r'^sales/print_sales/(?P<id>\d+)$', views.print_sales,name='print_sales'),
    url(r'^sales/print_sales_wholesale/(?P<id>\d+)$', views.print_sales_wholesale,name='print_sales'),
    url(r'^sales/view_sales/(?P<id>\d+)$', views.view_sales,name='view_sales'),
   
    url(r'^sales/edit_sales/(?P<id>\d+)$', views.edit_sales,name='edit_sales'),
    url(r'^sales/update_sales/(?P<id>\d+)$', views.update_sales,name='update_sales'),
    url(r'^sales/delete_sales/(?P<id>\d+)$', views.delete_sales,name='delete_sales'),
    url(r'^sales/delete_all_sales/$', views.delete_all_sales,name='delete_all_sales'),
    url(r'^sales/delete_wholesale_sales/(?P<id>\d+)$', views.delete_wholesale_sales,name='delete_wholesale_sales'),
    url(r'^sales/delete_all_wholesale_sales/$', views.delete_all_wholesale_sales,name='delete_all_wholesale_sales'),
    url(r'^sales_dashboard_ajax/$', views.sales_dashboard_ajax,name='sales_dashboard_ajax'),
    
]

store_billing_lite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('dashboard.urls')),
    url(r'',include('product.urls')),
    url(r'',include('returns.urls')),
    url(r'',include('reports.urls')),
    url(r'',include('sales.urls')),
    url(r'',include('settings_billing.urls')),

]

sales/models.py
from django.db import models
import datetime

from datetime import date
from django.utils import timezone
 
 

# Create your models here.
sale_type = (
            ('retail','retail'),
            ('wholesale','wholesale'),
            )



transaction_mode = (
            ('Cash','Cash'),
            ('Bank','Bank')
            )
cash_account = (
            ('General','General'),
            ('General','General'),
            ('General','General')
            )
 

class create_sales_table(models.Model):
	sales_product_ref_id=models.IntegerField()
	
	sales_invoice_no=models.IntegerField()
	sales_qty=models.IntegerField()

class create_sales_final(models.Model):
	sale_type=models.CharField(choices=sale_type,max_length=10)
	sales_date=models.DateField(null=True)
	sales_time=models.TimeField(null=True)
	subtotal=models.CharField(max_length=50)
	sale_invoice_ref=models.IntegerField()
	sales_special_discount=models.IntegerField()
	sales_total=models.CharField(max_length=50)
	sales_payment_received=models.IntegerField()
	sales_total_tax_amount=models.CharField(max_length=50)
	sales_total_discount_amount=models.IntegerField()
	sales_round_off=models.IntegerField()
	sales_transaction_mode=models.CharField(choices=transaction_mode,max_length=5)
	sales_cash_account=models.CharField(choices=cash_account,max_length=8)
	sales_payment_remainder_date=models.DateField(null=True)
	sales_payment_balance=models.CharField(max_length=50)
	sale_return_status=models.CharField(max_length=5)
	sales_taxable_amount=models.CharField(max_length=50)
	sales_printing=models.TextField()

class sale_totals(models.Model):
	sales_date=models.DateField(null=True)
	sales_totals=models.CharField(max_length=50)


class taxes(models.Model):
	tax_percent=models.IntegerField()
	sale_date=models.DateField(null=True)
	total_tax_amount=models.CharField(max_length=50)
	price_tax_amount=models.CharField(max_length=50)
	

class create_wholesale_sales_table(models.Model):
	sales_product_ref_id=models.IntegerField()
	
	sales_invoice_no=models.IntegerField()
	sales_qty=models.IntegerField()

class create_wholesale_sales_final(models.Model):
	sale_type=models.CharField(choices=sale_type,max_length=10)
	sales_date=models.DateField(null=True)
	sales_time=models.TimeField(null=True)
	subtotal=models.CharField(max_length=50)
	sale_invoice_ref=models.IntegerField()
	sales_special_discount=models.IntegerField()
	sales_total=models.CharField(max_length=50)
	sales_payment_received=models.IntegerField()
	sales_total_tax_amount=models.CharField(max_length=50)
	sales_total_discount_amount=models.IntegerField()
	sales_round_off=models.IntegerField()
	sales_transaction_mode=models.CharField(choices=transaction_mode,max_length=5)
	sales_cash_account=models.CharField(choices=cash_account,max_length=8)
	sales_payment_remainder_date=models.DateField(null=True)
	sales_payment_balance=models.CharField(max_length=50)
	sales_taxable_amount=models.CharField(max_length=50)
	sales_printing=models.TextField()
	
class sale_wholesale_totals(models.Model):
	sales_date=models.DateField(null=True)
	sales_totals=models.CharField(max_length=50)


class wholesale_taxes(models.Model):
	tax_percent=models.IntegerField()
	sale_date=models.DateField(null=True)
	total_tax_amount=models.CharField(max_length=50)
	price_tax_amount=models.CharField(max_length=50)


class reports(models.Model):
	prod_name=models.CharField(max_length=50)
	qty=models.CharField(max_length=50)
	unit=models.CharField(max_length=50)
	price=models.CharField(max_length=50)
	discount=models.CharField(max_length=50)
	taxable_amount=models.CharField(max_length=50)
	tax_percent=models.CharField(max_length=50)
	cgst=models.CharField(max_length=50)
	sgst=models.CharField(max_length=50)
	invoice_no=models.IntegerField()

sales/views.py
from django.shortcuts import render
from sales.forms import create_sale
from product.models import products,alternate_units,categorisation,sub_products,alternate_cost_price
from sales.models import create_sales_table,create_sales_final,sale_totals,taxes,create_wholesale_sales_table,create_wholesale_sales_final,sale_wholesale_totals,wholesale_taxes,reports
from dashboard.models import notification
from settings_billing.models import store_details
from itertools import*
import json       
from django.http import HttpResponse,HttpResponseRedirect 
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required 
from returns.models import sales_returned

# Create your views here.
@login_required(login_url='/login')
def dashboard_sales(request):
 
	active_sidebar1=2
	return render(request,'sales/dashboard_sales.html',{'active_sidebar1':active_sidebar1})

@login_required(login_url='/login')
def sales_details(request):
	sale_detail=create_sales_final.objects.all().order_by('-sale_invoice_ref')
	active_sidebar4=1
	activebar=1
	return render(request,'sales/sales_details.html',{'active_sidebar4':active_sidebar4,'activebar':activebar,'sale_detail':sale_detail})

@login_required(login_url='/login')
def sales_details_wholesale(request):
	sale_detail=create_wholesale_sales_final.objects.all().order_by('-sale_invoice_ref')
	active_sidebar4=1
	activebar=2
	return render(request,'sales/sales_details_wholesale.html',{'active_sidebar4':active_sidebar4,'activebar':activebar,'sale_detail':sale_detail})
 

@login_required(login_url='/login')
def stock_movement(request):
	active_sidebar4=2
	return render(request,'sales/stock_movement.html',{'active_sidebar4':active_sidebar4})


@login_required(login_url='/login')
def creating_sales(request):

	prodx=products.objects.all()
	unit_types=alternate_units.objects.all()
	cust_invoice=create_sales_table.objects.values_list('sales_invoice_no', flat=True)
	if cust_invoice==None:
		cust_invoice=0
	cust_invo_sum=max(cust_invoice)+1
	form = create_sale()
	active_sidebar2=2
	return render(request,'sales/create_sales.html',{'active_sidebar2':active_sidebar2,'form':form,'prodx':prodx,
		'unit_types':unit_types})

@login_required(login_url='/login')
def create_sales(request): 
	taxess=0

	prodx=products.objects.all()
	unit_types=alternate_units.objects.all()
	

	


	new_count=[]
	sl_no=[]
	bill_pro_name=[]
	bill_pro_hsn=[]
	bill_pro_qty=[]
	bill_pro_unit=[]
	bill_pro_price=[]
	bill_pro_disc=[]
	bill_pro_tax=[]
	bill_pro_cgst=[]
	bill_pro_sgst=[]
	bill_pro_igst=[]
	cess=[]
	bill_pro_total=[]
	bill_pro_taxable_amount=[]

	if request.method == 'POST':
		cust_invoice=create_sales_table.objects.values_list('sales_invoice_no', flat=True)
		if not cust_invoice:
			cust_invoice=[0]
		cust_invo_sum=max(cust_invoice)+1

		form=create_sale(request.POST)
		if request.POST.get("sale_type") == '1':
			counti=request.POST.getlist('counting')
			sp_disc=request.POST.get('sale_special_discount')
			for ccc in counti:

				new_count.append(int(ccc))
			counts=max(new_count)
			counts_int=int(counts)
			counts_int_sum=counts_int+1

			

			edits=[]
			for x in range(1,counts_int_sum):
				
				y=request.POST.get('selected_product%d'%x)
				if y is not None:
					edits.append(x)
			
			
			for x in edits:

				product_stock_info=products.objects.values_list('product_stock', flat=True).get(product_code=request.POST.get('selected_product%d'%x))
				product_stock_amount=request.POST.get('qty%d'%x)
				pro_stock=float(product_stock_info)-float(product_stock_amount)

				
				update_stock = products.objects.filter(product_code=request.POST.get('selected_product%d'%x)).update(product_stock=pro_stock)
				pro_id=products.objects.values_list('id', flat=True).get(product_code=request.POST.get('selected_product%d'%x))
				notify_update = notification.objects.filter(pk=pro_id).first()
				
				if notify_update == None:
					cre_notification=notification(
					id=products.objects.values_list('id', flat=True).get(pk=pro_id),
					product_name=products.objects.values_list('product_name', flat=True).get(pk=pro_id),
					product_stock=pro_stock,
					product_low_stock_limit=products.objects.values_list('product_low_stock_limit', flat=True).get(pk=pro_id),
					)
					cre_notification.save()
				notify_update_product_stock=notification.objects.filter(pk=pro_id).update(product_stock=pro_stock)
				cre_sales_table=create_sales_table(
				sales_product_ref_id=products.objects.values_list('id', flat=True).get(product_code=request.POST.get('selected_product%d'%x)),
				sales_qty=request.POST.get('qty%d'%x),
				sales_invoice_no=cust_invo_sum
				)
				cre_sales_table.save()
				store_ib=store_details.objects.latest('id')
				if request.POST.get('selected_unit%d'%x)=="0":
					bill_pro_pricess=float(products.objects.values_list('final_price', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))-float(products.objects.values_list('product_discount', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
				else:
					get_pr_id=products.objects.values_list('id', flat=True).get(product_code=request.POST.get('selected_product%d'%x))
					bill_pro_pricess=float(alternate_cost_price.objects.values_list('product_price', flat=True).get(product_ref_id=get_pr_id,unit_type_id=request.POST.get('selected_unit%d'%x)))-float(products.objects.values_list('product_discount', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
				if products.objects.values_list('final_price', flat=True).get(product_code=request.POST.get('selected_product%d'%x)) == "ex":
					gst=float(request.POST.get('tax_amount%d'%x))
					bill_pro_taxable_amo=(float(request.POST.get('sub_total%d'%x))-gst)-float(products.objects.values_list('product_discount', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
					if store_ib.cess_status=="YES":
						cess_value=(bill_pro_taxable_amo/100)
					else:
						cess_value=0
					total_bill=(float(request.POST.get('sub_total%d'%x))*float(request.POST.get('qty%d'%x)))+cess_value
				else:
					if request.POST.get('selected_unit%d'%x)=="0":
						bill_pro_taxable_amo=((float(products.objects.values_list('final_price', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))*100)/(100+float(products.objects.values_list('product_tax_category', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))))*float(request.POST.get('qty%d'%x))
					else:
						get_pr_id=products.objects.values_list('id', flat=True).get(product_code=request.POST.get('selected_product%d'%x))
						bill_pro_taxable_amo=((float(alternate_cost_price.objects.values_list('product_price', flat=True).get(product_ref_id=get_pr_id,unit_type_id=request.POST.get('selected_unit%d'%x)))*100)/(100+float(products.objects.values_list('product_tax_category', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))))*float(request.POST.get('qty%d'%x))
					bill_pro_taxable_amo=bill_pro_taxable_amo-float(products.objects.values_list('product_discount', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
					gst=(bill_pro_pricess*float(request.POST.get('qty%d'%x)))-bill_pro_taxable_amo
					if store_ib.cess_status=="YES":
						cess_value=(bill_pro_taxable_amo/100)
					else:
						cess_value=0
					total_bill=(bill_pro_pricess*float(request.POST.get('qty%d'%x)))+cess_value
				if store_ib.cess_status=="YES":
					bill_pro_name.append(products.objects.values_list('product_name', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
					bill_pro_hsn.append(products.objects.values_list('product_hsn', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
					bill_pro_qty.append(float(request.POST.get('qty%d'%x)))
					bill_pro_unit.append(request.POST.get('selected_post_unit%d'%x).split('(', 1)[1].split(')')[0])
					bill_pro_price.append(bill_pro_pricess)
					bill_pro_disc.append(float(request.POST.get('discount%d'%x)))
					bill_pro_tax.append(products.objects.values_list('product_tax_category', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))
					bill_pro_cgst.append(gst/2)
					bill_pro_sgst.append(gst/2)
					cess.append(bill_pro_taxable_amo/100)



					save_report=reports(
					prod_name=products.objects.values_list('product_name', flat=True).get(product_code=request.POST.get('selected_product%d'%x)),
					qty=request.POST.get('qty%d'%x),
					unit=request.POST.get('selected_post_unit%d'%x).split('(', 1)[1].split(')')[0],
					price=bill_pro_pricess,
					discount=float(request.POST.get('discount%d'%x)),
					taxable_amount=bill_pro_taxable_amo,
					tax_percent=products.objects.values_list('product_tax_category', flat=True).get(product_code=request.POST.get('selected_product%d'%x)),
					cgst=gst/2,
					sgst=gst/2,
					invoice_no=cust_invo_sum
					)
					save_report.save()



					#cess_value=(bill_pro_taxable_amo/100)
					
					#bill_pro_taxable_amount.append(float(products.objects.values_list('product_price', flat=True).get(product_code=request.POST.get('selected_product%d'%x)))-float(products.objects.values_list('product_cost', flat=True).get(product_code=request.POST.get('selected_product%d'%x))))
					bill_pro_total.append(total_bill)
					billing_total=float(request.POST.get('sale_total'))
					bill_pro_taxable_amount.append(bill_pro_taxable_amo)

					import pandas as pd
					df=pd.DataFrame(list(zip(bill_pro_name,bill_pro_hsn,bill_pro_qty,bill_pro_unit,bill_pro_price,bill_pro_tax,bill_pro_disc,bill_pro_taxable_amount,bill_pro_cgst,bill_pro_sgst,cess,bill_pro_total)),columns=['b','c','d','e','f','g','h','i','j','k','l','m'])
					
					aab=df.groupby(['b','e']).agg({'c': 'first','d': 'sum','f': 'sum','g': 'sum','h': 'sum','i': 'first','j': 'sum','k': 'sum','l': 'sum','m': 'sum'}).reset_index().round(3)
					sl=[i for i in range(1,len(aab.index)+1)]
					se = pd.Series(sl)
					aab['n'] = se.values

sales/templates/sales/sales_details.html
{%extends 'dashboard/layout.html'%}
{% load static %}

{%block content%}




<div class="content-wrapper">

<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">Sales</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>


<section class="content">	
			


<div class="row">
		  
		<div class="col-12">
         
         <div class="box">
            <div class="box-header with-border">
            	<form class="form" method="post" action="{% url 'sales:delete_all_sales'%}">
					 {% csrf_token %}
        <ul id="main-menu" class="sm sm-blue" style="display: inline-block;">
		<li><a href="{% url 'sales:sales_details'%}" class="{% if activebar == 1 %}current{% endif %}"></i>Retail</a></li>
		<li><a href="{% url 'sales:sales_details_wholesale'%}" class="{% if activebar == 2 %}current{% endif %}"></i>Wholesale</a></li>
		</ul>
              <span class="icon-input-btn"><span class="glyphicon glyphicon-trash"></span><input type="submit" class="btn btn-info btn-md" value="Delete" id="deletesal"></span>
            </div>
            <!-- /.box-header -->
                  <div class="box-body">
				<div class="table-responsive">
				  <table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th> <input type="checkbox" id="ckbCheckAll" /><label for="ckbCheckAll"></label></th>
							<input type="text" name="checked_pro" value="0" id="checked_pro" style="display: none;">
							<th>ID</th>
							<th>TIME</th>
							<th>SUBTOTAL</th>
							<th>SPECIAL<br>DISCOUNT</th>
							<th>TOTAL</th>
							<th>PAYMENT<br>RECIEVED</th>
							<th>BALANCE</th>
							<th>ACTION</th>
						</tr>
					</thead>
					<tbody>
						{% for x in sale_detail%}
						<tr>
							<td><input type="checkbox" id="checkbox_{{x.id}}" class="filled-in" name='check' value="{{x.id}}">
								<label for="checkbox_{{x.id}}"></label>
								</td>
							<td>{{x.sale_invoice_ref}}</td>
							<td>{{x.sales_date}}<br>{{x.sales_time}}</td>
							<td>{{x.subtotal}}</td>
							<td>{{x.sales_special_discount}}</td>
							<td>{{x.sales_total}}</td>
							<td>{{x.sales_total}}</td>
							<td>{{x.sales_payment_balance}}</td>
							<td style="white-space:nowrap;">
							{% if x.sale_return_status == "0" %}<span style="font-size:15px;><input type="button" class="btn btn-circle btn-info btn-sm mb-5" onclick="window.location.href='../sales/delete_sales/{{x.id}}'">
								<i class="mdi mdi-delete"style="font-size:20px"></i>
							</span>&nbsp;{% endif %}
							{% if x.sale_return_status == "1" %}<span style="font-size:15px;opacity: 0.6;><input type="button" class="btn btn-circle btn-info btn-sm mb-5" id="disable_delete"">
								<i class="mdi mdi-delete"style="font-size:20px"></i>
							</span>&nbsp;{% endif %}
							<span style="font-size:15px;><input type="button" class="btn btn-circle btn-info btn-sm mb-5" onclick="window.location.href='../sales/print_sales/{{x.id}}'">
								<i class="mdi mdi-printer"style="font-size:20px"></i></span>
						</tr>
						{% endfor %}
						

					</tbody>
					<tfoot>
						<tr style="display: none;">
							<th></th>
							<th>ID</th>
							<th>TIME</th>
							<th>SUBTOTAL</th>
							<th>SPECIAL<br>DISCOUNT</th>
							<th>TOTAL</th>
							<th>PAYMENT<br>RECIEVED</th>
							<th>BALANCE</th>
							<th>ACTION</th>
						</tr>
					</tfoot>
				</table>
				</div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->      
        
        </div>


</div>
<script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#ckbCheckAll').on('click',function(){
        if(this.checked){
            $('.filled-in').each(function(){
                this.checked = true;
            });
        }else{
             $('.filled-in').each(function(){
                this.checked = false;
            });
        }
    });
    
    $('.filled-in').on('click',function(){
        if($('.filled-in:checked').length == $('.filled-in').length){
            $('#ckbCheckAll').prop('checked',true);
        }else{
            $('#ckbCheckAll').prop('checked',false);
        }
    });
});

 	$(document).ready(function() {
        $("#deletesal").click(function(){
        	
            var favorite = [];
            $.each($("input[name='check']:checked"), function(){            
                favorite.push($(this).val());
                $('#checked_pro').val(favorite);
                
            });
            
        });
    });


</script>

   {%endblock%}	

sales/templates/sales/sales_details_wholesale.html
{%extends 'dashboard/layout.html'%}
{% load static %}

{%block content%}




<div class="content-wrapper">

<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">Sales-Wholesale</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>


<section class="content">	
			


<div class="row">
		  
		<div class="col-12">
         
         <div class="box">
            <div class="box-header with-border">
            	<form class="form" method="post" action="{% url 'sales:delete_all_wholesale_sales'%}">
					 {% csrf_token %}
        <ul id="main-menu" class="sm sm-blue" style="display: inline-block;">
		<li><a href="{% url 'sales:sales_details'%}" class="{% if activebar == 1 %}current{% endif %}"></i>Retail</a></li>
		<li><a href="{% url 'sales:sales_details_wholesale'%}" class="{% if activebar == 2 %}current{% endif %}"></i>Wholesale</a></li>
		</ul>
              <span class="icon-input-btn"><span class="glyphicon glyphicon-trash"></span><input type="submit" class="btn btn-info btn-md" value="Delete" id="deletesal"></span>
            </div>
            <!-- /.box-header -->
                  <div class="box-body">
				<div class="table-responsive">
				  <table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th> <input type="checkbox" id="ckbCheckAll" /><label for="ckbCheckAll"></label></th>
							<input type="text" name="checked_pro" value="0" id="checked_pro" style="display: none;">
							<th>ID</th>
							<th>TIME</th>
							<th>SUBTOTAL</th>
							<th>SPECIAL<br>DISCOUNT</th>
							<th>TOTAL</th>
							<th>PAYMENT<br>RECIEVED</th>
							<th>BALANCE</th>
							<th>ACTION</th>
						</tr>
					</thead>
					<tbody>
						{% for x in sale_detail%}
						<tr>
							<td><input type="checkbox" id="checkbox_{{x.id}}" class="filled-in" name='check' value="{{x.id}}">
								<label for="checkbox_{{x.id}}"></label>
								</td>
							<td>{{x.sale_invoice_ref}}</td>
							<td>{{x.sales_date}}<br>{{x.sales_time}}</td>
							<td>{{x.subtotal}}</td>
							<td>{{x.sales_special_discount}}</td>
							<td>{{x.sales_total}}</td>
							<td>{{x.sales_total}}</td>
							<td>{{x.sales_payment_balance}}</td>
							<td style="white-space:nowrap;">
							<span style="font-size:15px;><input type="button" class="btn btn-circle btn-info btn-sm mb-5" onclick="window.location.href='../sales/delete_wholesale_sales/{{x.id}}'">
								<i class="mdi mdi-delete"style="font-size:20px"></i>
							</span>&nbsp;
							<span style="font-size:15px;><input type="button" class="btn btn-circle btn-info btn-sm mb-5" onclick="window.location.href='../sales/print_sales_wholesale/{{x.id}}'">
								<i class="mdi mdi-printer"style="font-size:20px"></i></span>
							<!-- {% if x.sale_return_status == "1" %}<span style="font-size:15px;opacity: 0.6;><input type="button" class="btn btn-circle btn-info btn-sm mb-5" id="disable_delete"">
								<i class="mdi mdi-delete"style="font-size:20px"></i>
							</span>&nbsp;{% endif %} -->
							
						</tr>
						{% endfor %}
						

					</tbody>
					<tfoot>
						<tr style="display: none;">
							<th></th>
							<th>ID</th>
							<th>TIME</th>
							<th>SUBTOTAL</th>
							<th>SPECIAL<br>DISCOUNT</th>
							<th>TOTAL</th>
							<th>PAYMENT<br>RECIEVED</th>
							<th>BALANCE</th>
							<th>ACTION</th>
						</tr>
					</tfoot>
				</table>
				</div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->      
        
        </div>


</div>
<script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#ckbCheckAll').on('click',function(){
        if(this.checked){
            $('.filled-in').each(function(){
                this.checked = true;
            });
        }else{
             $('.filled-in').each(function(){
                this.checked = false;
            });
        }
    });
    
    $('.filled-in').on('click',function(){
        if($('.filled-in:checked').length == $('.filled-in').length){
            $('#ckbCheckAll').prop('checked',true);
        }else{
            $('#ckbCheckAll').prop('checked',false);
        }
    });
});

 	$(document).ready(function() {
        $("#deletesal").click(function(){
        	
            var favorite = [];
            $.each($("input[name='check']:checked"), function(){            
                favorite.push($(this).val());
                $('#checked_pro').val(favorite);
                
            });
            
        });
    });


</script>

   {%endblock%}	