product/urls.py
from product import views
from django.conf.urls import url

app_name='product'
urlpatterns = [
    url(r'^product_details/$', views.product_details,name='product_details'),   
    url(r'^create_barcode/$', views.create_barcode,name='create_barcode'),
    url(r'^create_barcode_id/(?P<id>\d+)$', views.create_barcode_id,name='create_barcode_id'),
    url(r'^barcode_generator/$', views.barcode_generator,name='barcode_generator'),
    url(r'^product_upload/$', views.product_upload,name='product_upload'),
    url(r'^create_products/$', views.create_products,name='create_products'),
    # url(r'^create_update_products/$', views.create_update_products,name='create_update_products'),
    url(r'^create_product_ajax/$', views.create_product_ajax,name='create_product_ajax'),
    url(r'^generate_code_ajax/$', views.generate_code_ajax,name='generate_code_ajax'),
    url(r'^update_product_ajax/$', views.update_product_ajax,name='update_product_ajax'),
    url(r'^product/edit_products/(?P<id>\d+)$',views.edit_products,name='edit_products'),
    url(r'^product/update_products/$',views.update_products,name='update_products'),
    url(r'^update_stock/$', views.update_stock,name='update_stock'),
    url(r'^del_products/(?P<id>\d+)$',views.del_products,name='del_products'),
    url(r'^delete_all_product/', views.delete_all_product,name='delete_all_product'),
]

sales/urls.py
from sales import views
from django.conf.urls import url

app_name='sales'
urlpatterns = [
    url(r'^sales/$', views.sales_details,name='sales_details'),
    url(r'^sales_wholesale/$', views.sales_details_wholesale,name='sales_details_wholesale'),
    url(r'^dashboard_sales/$', views.dashboard_sales,name='dashboard_sales'),
   
    url(r'^stock_movement/$', views.stock_movement,name='stock_movement'),
    url(r'^create_sales/$', views.create_sales,name='create_sales'),
    url(r'^creating_sales/$', views.creating_sales,name='creating_sales'),
   
    url(r'^create_sales_ajax/$', views.create_sales_ajax,name='create_sales_ajax'),
    url(r'^sales/print_sales/(?P<id>\d+)$', views.print_sales,name='print_sales'),
    url(r'^sales/print_sales_wholesale/(?P<id>\d+)$', views.print_sales_wholesale,name='print_sales'),
    url(r'^sales/view_sales/(?P<id>\d+)$', views.view_sales,name='view_sales'),
   
    url(r'^sales/edit_sales/(?P<id>\d+)$', views.edit_sales,name='edit_sales'),
    url(r'^sales/update_sales/(?P<id>\d+)$', views.update_sales,name='update_sales'),
    url(r'^sales/delete_sales/(?P<id>\d+)$', views.delete_sales,name='delete_sales'),
    url(r'^sales/delete_all_sales/$', views.delete_all_sales,name='delete_all_sales'),
    url(r'^sales/delete_wholesale_sales/(?P<id>\d+)$', views.delete_wholesale_sales,name='delete_wholesale_sales'),
    url(r'^sales/delete_all_wholesale_sales/$', views.delete_all_wholesale_sales,name='delete_all_wholesale_sales'),
    url(r'^sales_dashboard_ajax/$', views.sales_dashboard_ajax,name='sales_dashboard_ajax'),
    
]

store_billing_lite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('dashboard.urls')),
    url(r'',include('product.urls')),
    url(r'',include('returns.urls')),
    url(r'',include('reports.urls')),
    url(r'',include('sales.urls')),
    url(r'',include('settings_billing.urls')),

]

product/views.py
from django.shortcuts import render 
from django.http import HttpResponse,HttpResponseRedirect
from product.forms import create_product,create_purchases,create_purchase_invoices,create_asset_purchases,create_barcodes,uploading_products
from product.models import products,categorisation,alternate_units,sub_products,alternate_cost_price
from dashboard.models import notification
from itertools import*
import json    
import barcode   
import random  
from barcode.writer import ImageWriter
from PIL import Image
import xlrd 
from django.core.files import File
from django.contrib.auth.models import User 
from django.contrib.auth.decorators import login_required
import re
from settings_billing.models import store_details
# Create your views here.
@login_required(login_url='/login')
def product_details(request):
	
	pro_details=products.objects.all().order_by('-id')
	active_sidebar1=1
	return render(request,'product/product_details.html',{'active_sidebar1':active_sidebar1,'pro_details':pro_details})
	
@login_required(login_url='/login')
def purchase_details(request):

	purch_details=purchase_final.objects.all()
	active_sidebar2=1
	return render(request,'product/purchase_details.html',{'active_sidebar2':active_sidebar2,'purch_details':purch_details})
	
@login_required(login_url='/login')
def create_barcode_id(request,id):
	
	prodx=products.objects.all()
	pro_name=products.objects.values_list('product_name', flat=True).get(pk=id)
	form=create_barcodes()
	active_sidebar2=1
	return render(request,'product/create_barcode.html',{'active_sidebar2':active_sidebar2,'form':form,'prodx':prodx,"prid":id,"pro_name":pro_name})
	
@login_required(login_url='/login')
def create_barcode(request):
	
	prodx=products.objects.all()
	form=create_barcodes()
	active_sidebar2=1
	return render(request,'product/create_barcode.html',{'active_sidebar2':active_sidebar2,'form':form,'prodx':prodx})

@login_required(login_url='/login')
def barcode_generator(request):

	if request.method == 'POST':
		
		prod_id=request.POST.get('selected_product')
		unit=request.POST.get('unit')
		prod_name=products.objects.values_list('product_name', flat=True).get(pk=prod_id)
		prod_cost=float(products.objects.values_list('product_price', flat=True).get(pk=prod_id))+float(products.objects.values_list('product_tax_amount', flat=True).get(pk=prod_id))
		prod_cost=round(prod_cost)
		prod_code=products.objects.values_list('product_code', flat=True).get(pk=prod_id)
		#return HttpResponse(len(prod_code))
		#length=len(list(filter(lambda m:m.isdigit(), str(prod_code))))
		length=len(prod_code)
		image=barcode.get_barcode_class('code128')
		image_bar=image('{0}'.format(prod_code), writer=ImageWriter())
		file=open('/var/www/html/django/store_billing_lite/static/images/barcode/vj1.png',"wb")
		image_bar.write(file)
		

		file = '/var/www/html/django/store_billing_lite/static/images/barcode/vj1.png'
		if length==3:
			im = Image.open(file)
			crop_rectangle = (20, 168, 200, 195)
			cropped_im = im.crop(crop_rectangle)
			cropped_im.save(file)
		elif length==4:
			im = Image.open(file)
			crop_rectangle = (20, 165, 225, 196)
			cropped_im = im.crop(crop_rectangle)
			cropped_im.save(file)
		elif length==5:
			im = Image.open(file)
			crop_rectangle = (20, 162, 260, 198)
			cropped_im = im.crop(crop_rectangle)
			cropped_im.save(file)
		elif length==6:
			im = Image.open(file)
			crop_rectangle = (20, 163, 270, 200)
			cropped_im = im.crop(crop_rectangle)
			cropped_im.save(file)
		else:
			im = Image.open(file)
			crop_rectangle = (20, 165, 290, 200)
			cropped_im = im.crop(crop_rectangle)
			cropped_im.save(file)
		unit=int(unit)

		unit_list=[]
		for x in range(unit):
			unit_list.append(x)	
	active_sidebar4=1
	store_info=store_details.objects.latest('id')
	return render(request,'barcodes/bar.html',{'unit_list':unit_list,'prod_code':prod_code,'prod_name':prod_name,
		'prod_cost':prod_cost,'store_info':store_info})
	
############################################################################################################

 
 
 
################################# create product ##########################################################
@login_required(login_url='/login')
def create_products(request):

	prodx=products.objects.all()
	repeat_category=products.objects.order_by().values_list('category_ref', flat=True).distinct()
	repeat_brand=products.objects.order_by().values_list('brand_ref', flat=True).distinct()
	units=categorisation.objects.all()
	
	if request.method == 'POST':
		form=create_product(request.POST)
		pro_name=request.POST['product']
		if pro_name.isdigit():
			if form.is_valid():
				old_stock=products.objects.values_list('product_stock', flat=True).get(pk=pro_name)
				
				update_stock = products.objects.filter(pk=pro_name).update(product_stock=int(request.POST.get('product_stock'))+int(old_stock))
				update_limit_stock = products.objects.filter(pk=pro_name).update(product_low_stock_limit=request.POST.get('product_low_stocklimit'))
				# update_cost = products.objects.filter(pk=pro_name).update(product_cost=form.cleaned_data['product_cost'])
				# update_mrp = products.objects.filter(pk=pro_name).update(product_price=form.cleaned_data['product_price'])
				# update_wholesale = products.objects.filter(pk=pro_name).update(product_wholesale_price=form.cleaned_data['product_wholesale_price'])
				# update_disc = products.objects.filter(pk=pro_name).update(product_discount=form.cleaned_data['product_discount'])
				# product_code=form.cleaned_data['product_code']
				# product_hsn=form.cleaned_data['product_hsn']
				# product_alternate_cost=form.cleaned_data['product_alter_cost']
				# product_alternate_price=form.cleaned_data['product_alter_price']
				
				notify_update = notification.objects.filter(pk=pro_name).first()
				
				if notify_update == None:
					cre_notification=notification(
					id=products.objects.values_list('id', flat=True).get(pk=pro_name),
					product_name=products.objects.values_list('product_name', flat=True).get(pk=pro_name),
					product_stock=request.POST.get('product_stock'),
					product_low_stock_limit=request.POST.get('product_low_stocklimit')
					)
					cre_notification.save()

				notify_update_product_stock=notification.objects.filter(pk=pro_name).update(product_stock=request.POST.get('product_stock'))
				notify_update_product_low_stock_limit=notification.objects.filter(pk=pro_name).update(product_low_stock_limit=request.POST.get('product_low_stocklimit'))
		
				
				
			else:
				return HttpResponse(form.errors)
			return HttpResponseRedirect("/create_products")

		else:
			
			if form.is_valid():
				tax_inc=request.POST.get('taxes_stat')
				
				if tax_inc=="True":
					tax_stat="in"
					tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST.get('product_price'))
					tax_amount=float(tax_amount)/100
					prod_price=float(request.POST.get('product_price'))-tax_amount
					final_pro_price=request.POST.get('product_price')
					taxable_amount=(float(request.POST.get('product_price'))*100)/(100+float(request.POST.get('product_tax_category')))

					# alter_tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST['product_alter_price0'])
					# alter_tax_amount=float(tax_amount)/100
					# alter_prod_price=float(request.POST['product_alter_price0'])-tax_amount

					# alter_final_pro_price=request.POST['product_alter_price']
					# alter_taxable_amount=(float(request.POST['product_alter_price'])*100)/(100+float(request.POST.get('product_tax_category')))
				else:
					tax_stat="ex"
					tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST.get('product_price'))
					tax_amount=float(tax_amount)/100
					prod_price=float(request.POST.get('product_price'))+tax_amount
					final_pro_price=float(request.POST.get('product_price'))+tax_amount
					taxable_amount=float(request.POST.get('product_price'))

					# alter_tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST['product_alter_price0'])
					# alter_tax_amount=float(tax_amount)/100
					# alter_prod_price=float(request.POST['product_alter_price0'])+tax_amount

					# alter_final_pro_price=float(request.POST['product_alter_price'])+tax_amount
					# alter_taxable_amount=float(request.POST['product_alter_price'])

				#wholesale............................

				if tax_inc=="True":
					
					wholesale_tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST.get('product_wholesale_price'))
					wholesale_tax_amount=float(wholesale_tax_amount)/100
					wholesale_prod_price=float(request.POST.get('product_wholesale_price'))-wholesale_tax_amount
					wholesale_final_pro_price=request.POST.get('product_wholesale_price')
					wholesale_taxable_amount=(float(request.POST.get('product_wholesale_price'))*100)/(100+float(request.POST.get('product_tax_category')))
				else:
					
					wholesale_tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST.get('product_wholesale_price'))
					wholesale_tax_amount=float(wholesale_tax_amount)/100
					wholesale_prod_price=float(request.POST.get('product_wholesale_price'))+wholesale_tax_amount
					wholesale_final_pro_price=float(request.POST.get('product_wholesale_price'))+wholesale_tax_amount
					wholesale_taxable_amount=float(request.POST.get('product_wholesale_price'))

				# return HttpResponse(request.POST.get('product_tax_category'))
				tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST.get('product_price'))
				tax_amount=float(tax_amount)/100
				wholesale_tax_amount=float(request.POST.get('product_tax_category'))*float(request.POST.get('product_wholesale_price'))
				wholesale_tax_amount=float(wholesale_tax_amount)/100
				dif_price_cost=float(request.POST.get('product_price'))-float(request.POST.get('product_cost'))
				price_tax_amount=float(request.POST.get('product_tax_category'))*dif_price_cost
				price_tax_am=float(price_tax_amount)/100

product/templates/product/create_barcode.html
{%extends 'dashboard/layout.html'%}
{% load static %}

{%block content%}




<div class="content-wrapper">

<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">CREATE PRODUCT</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>

<section class="content"> 		

<div class="row">
		  
		<div class="col-12">
         
         
            <!-- /.box-header -->
            <div class="row">			  
		<div class="col-lg-4 col-12">
			  <div class="box">
				<div class="box-header with-border">
				  <h4 class="box-title">BASIC INFO</h4>			
					<ul class="box-controls pull-right">
					 
					  <li><a class="box-btn-slide" href="#"></a></li>	
					 
					</ul>
				</div>
				<!-- /.box-header -->
				<form class="form" method="post" action="{% url 'product:barcode_generator'%}" id="form_id">
					 {% csrf_token %}
					<div class="box-body">
					
						<div class="row">
						  <div class="col-md-12">
				
							<div class="form-group">
							  <label >PRODUCT</label>
							  <select required class="form-control select2"id="select_id" name="selected_product" value="1">
							  	<option selected value="{{prid}}">{{pro_name}}</option>
								{% for x in prodx %}<option value="{{x.id}}">{{x.product_name}}</option>{% endfor %}
							</select>
							</div>
						  </div>
						</div>
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >UNIT</label>
							<input class="form-control" type="number" placeholder="unit" id="qty_id" name="unit" value="10">
							</div>
						  </div>
                       </div>
                       
					 
					<!-- /.box-body -->
					</div>  
          
			  </div>
			
			  <!-- /.box -->			
		</div>  
			
		</div>  
</div>

            </div>
<input type="submit" class="btn btn-success" value="Submit">
            <!-- /.box-body -->
            </form>
         </div>
 <script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script>
  <script src="{% static 'assets/vendor_components/select2/dist/js/select2.full.js' %}"></script>

<script type="text/javascript">
	$('.select2').select2({
    		minimumInputLength: 1,
    		allowClear: true,
			placeholder:'Product',
			width:'100%'
		});
	$('#form_id').submit(function (e, params) {
        var localParams = params || {};

        if (!localParams.send) {
            e.preventDefault();
        }

           //additional input validations can be done hear

    swal({
              title: 'Barcode Generated!',
  type: 'success',
    timer: 500,
    showConfirmButton: false
    
            }, function (isConfirm) {
               
                    $(e.currentTarget).trigger(e.type, { 'send': true });
                
        });
});
</script>




   {%endblock%}	

product/templates/product/create_products.html
{%extends 'dashboard/layout.html'%}
{% load static %}

{%block content%}


  


<div class="content-wrapper">
<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">CREATE PRODUCT</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>

<section class="content">	

<div class="row">
		  
		<div class="col-12">
         
         
            <!-- /.box-header -->
            <div class="row">			  
		<div class="col-lg-4 col-12">
			  <div class="box">
				<div class="box-header with-border">
				  <h4 class="box-title">BASIC INFO</h4>			
					<ul class="box-controls pull-right">
					 
					  <li><a class="box-btn-slide" href="#"></a></li>	
					 
					</ul>
				</div>
				<!-- /.box-header -->
				<form class="form" method="post" action="{% url 'product:create_products'%}">
					 {% csrf_token %}
					<div class="box-body">
					
						<div class="row">
						  <div class="col-md-12">
				
							<div class="form-group">
							  <label >Name</label>
							  {{form.product_name}}
							</div>
						  </div>

						 
						</div>
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Code</label>
							{{form.product_code}}
							</div>
						  </div>
                       </div>
                       <div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Hsn</label>
							  {{form.product_hsn}}
							</div>
						  </div>
                       </div>
                       <div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Category</label>
							  <select required class="form-control select2 cat" width="300" id="cat_id" name="category">
							<option></option>
								{% for x in prodx %}<option value="{{x.category_ref}}">{{x.category_ref}}</option>{% endfor %}</select>
							 
							  </select>
							</div>
						  </div>
                       </div>
                         <div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Brand</label>
						<select required class="form-control select2 brand" width="300" id="brand_id" name="brand">
							<option></option>
								{% for x in prodx %}<option value="{{x.brand_ref}}">{{x.brand_ref}}</option>{% endfor %}</select>
							
							  </select>
							</div>
						  </div>
                       </div>
                        <div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Unit type</label>
							<select required class="form-control select2 unit" width="300" id="unit_id" name="unit">
							<option></option>
								{% for x in units %}<option value="{{x.id}}">{{x.product_unit_type}}</option>{% endfor %}</select>
							
							  </select> 
							</div>
						  </div>
                       </div>
                       <div class="row">
                       	<div class="col-md-6">
							<div class="form-group">
							  <label >Stock</label>
							  {{form.product_stock}}
							</div>
						  </div>
						  <div class="col-md-6">
							<div class="form-group">
							  <label >Low stock limit </label>
							 {{form.product_low_stocklimit}}
							</div>
						  </div>
						</div>
						
					
						 
							
									
		
					<!-- /.box-body -->
					</div>  
          
			  </div>
			  

			  <!-- /.box -->			
		</div>  

		  
		<div class="col-lg-4 col-12">
			  <div class="box">
				<div class="box-header with-border">
				  <h4 class="box-title">Cost & Price</h4>			
					<ul class="box-controls pull-right">
					
					  <li><a class="box-btn-slide" href="#"></a></li>	
					
					</ul>
				</div>
				<!-- /.box-header -->
				<form class="form">
					<div class="box-body">
					
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Cost</label>
							 {{form.product_cost}}
							</div>
						  </div>
						 
						</div>
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >MRP</label>
							 {{form.product_price}}
							</div>
						  </div>
						 
						</div>
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Wholesale Price</label>
							{{form.product_wholesale_price}}
							</div>
						  </div>
						 
						</div>
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Tax Category</label>
							<select required class="form-control select2 tax" width="300" id="product_tax_category_id" name="product_tax_category">
							<option></option>
								{% for x in percent %}<option value="{{x}}">{{x}}%</option>{% endfor %}</select>
						  </div>
						</div>
						 
						</div>
						<div class="c-inputs-stacked"> 
								{{form.product_tax_included}}
								<label for="checkbox_123" class="block">Is tax included</label>
								{{form.product_expiration}}
								<label for="checkbox_234" class="block">Is Expired</label>
								
							</div>
						<div class="row">
						  <div class="col-md-12">
							<div class="form-group">
							  <label >Discount</label>
							  {{form.product_discount}}
							</div>
						  </div>
						 
						</div>


						
		</div>  
</div> 
			  <!-- /.box -->			
		</div><div class="col-lg-4 col-12" style="display: none;">
		  <!-- SELECT2 EXAMPLE -->
		  <div class="box">
			<div class="box-header with-border">
			  <h4 class="box-title">Alterntive Unit Price</h4>
				<ul class="box-controls pull-right">
				  
				  <li><a class="box-btn-slide" href="#"></a></li>	
				</ul>
			</div>
			<!-- /.box-header -->
			<div class="box-body pb-0">
			  <div class="row">
				<div class="col-md-4 col-12">
				  <div class="form-group">
					<label>UNIT</label>
					<select required class="form-control alternate_units" width="300" id="alter_unit_id" name="alter_units">
					<option value="0">..........</option>
					   
					</select>
				  </div>
				  <!-- /.form-group -->
				</div>
				<!-- /.col -->
				<div class="col-md-4 col-12">
				  <div class="form-group">
					<label>Cost</label>
					 {{form.product_alter_cost}}
					</select>
				  </div>
				  <!-- /.form-group -->
				</div>
				<!-- /.col -->
				<div class="col-md-4 col-12">
				  <div class="form-group">
					<label>Price</label>
					{{form.product_alter_price}}
					 
				
				  </div>
				  <!-- /.form-group -->
					
				</div>
				<!-- /.col -->
				
				<!-- /.col -->
			  </div>
			  <!-- /.row -->
			</div>
			<!-- /.box-body -->
		  </div>
		  <!-- /.box -->
        </div> 
		  

            </div>
<input type="submit" class="btn btn-success" value="Submit">
            <!-- /.box-body -->
            </form>
         </div>
</div>
</div>
 
<script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script>
<script src="{% static 'assets/vendor_components/select2/dist/js/select2.full.js' %}"></script>

<script>
	//category


    	$('.cat').select2({
    		minimumInputLength: 1,
    		allowClear: true,
			placeholder:'Category',
			width:'100%',
			tags: true,
    createTag: function (params) {

        var term = $.trim(params.term);

        if (term === '') {
            return null;
        }
        return {
            id: term,
            text:'create ' +term ,  // add text....
            newTag: true // add additional parameters
        }
    },
    insertTag: function (data, tag) {
    // Insert the tag at the end of the results
    data.push(tag);
  }
}).on('select2:select', function(e) {

    $(this).next('.select2-container').find('.select2-selection__rendered:contains("create ")').text(function(idx, txt) {
    	
    	rep=txt.replace('create ', '');
    	rep=rep.substring(1);
        return rep;
    });
});


//brand


    	$('.brand').select2({
    		minimumInputLength: 1,
    		allowClear: true,
			placeholder:'Brand',
			width:'100%',
		tags: true,
    createTag: function (params) {

        var term = $.trim(params.term);

        if (term === '') {
            return null;
        }
        return {
            id: term,
            text:'create ' +term ,  // add text....
            newTag: true // add additional parameters
        }
    },
    insertTag: function (data, tag) {
    // Insert the tag at the end of the results
    data.push(tag);
  }
	}).on('select2:select', function(e) {

    $(this).next('.select2-container').find('.select2-selection__rendered:contains("create ")').text(function(idx, txt) {
    	
    	rep=txt.replace('create ', '');
    	rep=rep.substring(1);
        return rep;
    });
	});


//unit   


	$('.unit').select2({
    		
    		allowClear: true,
			placeholder:'unit',
			width:'100%',
		
		});

	$('.tax').select2({
    		minimumInputLength: 1,
    		allowClear: true,
			placeholder:'Tax Category',
			width:'100%',
		
		});


$(document).on('change','#unit_id',function(e){
 
 	e.preventDefault();
 	$.ajax({
 		type:'POST',
 		url:'/create_product_ajax/',
 		data:{
 			action:'selection2',
 			selection:$('#unit_id').val(),
 			csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
 		},
 		dataType: "json",
 		success:function(data){
 			
 			$('.alternate_units').html(data['alter_unit']);
 			console.log(data['alter_unit']);
 			
 			
 			
 		}
 	});
 });


</script>



   {%endblock%}	

product/templates/product/product_upload.html
{%extends 'dashboard/layout.html'%}
{% load static %}

{%block content%}




 
<div class="content-wrapper">
<div class="content-header">
		<div class="d-flex align-items-center">
			<div class="mr-auto w-p50">
				<h3 class="page-title">UPLOAD PRODUCT LIST</h3>
				<div class="d-inline-block align-items-center">
					<nav>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
							<li class="breadcrumb-item active" aria-current="page">Control</li>
						</ol>
					</nav>
				</div>
			</div>
			
    </div>
  </div>

<section class="content"> 			



		
     
      <div class="row">
        <!-- left column -->
        <div class="col-xl-8 col-lg-12">
          <!-- general form elements -->
          <div class="box">
            <div class="box-header with-border">
              <h4 class="box-title">Basic Info</h4>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           <form class="form" method="post" action="{% url 'product:product_upload'%}" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="box-body">
              
                
                <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  {{form.excel_file}}

                  
                </div>
               
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <input type="submit" class="btn btn-danger" value="Submit">
              </div>
            </form>
          </div>
					
				
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->      
        </div>
        





   {%endblock%}	