dashboard/urls.py
from dashboard import views
from django.conf.urls import url
from django.urls import path
app_name='dashboard'
urlpatterns = [
	path('layout', views.layout,name='layout'), 
	path('indexs', views.indexing,name='indexs'),
	path('', views.indexing,name='indexs'),
	path('logout', views.user_logout,name='logout'),
	path('layout', views.layout,name='layout'),
	path('error_page', views.error_page,name='error_page'),
	url(r'^create_table_ajax/$', views.create_table_ajax,name='create_table_ajax'),
	url(r'^create_table_ajaxing/$', views.create_table_ajaxing,name='create_table_ajaxing'),
	url(r'^login/$', views.user_login,name='login'),
	url(r'^searching_product/$', views.searching_product,name='searching_product'),
	url(r'^clearall_ajax/$', views.clearall_ajax,name='clearall_ajax'),
]

product/urls.py
from product import views
from django.conf.urls import url

app_name='product'
urlpatterns = [
    url(r'^product_details/$', views.product_details,name='product_details'),   
    url(r'^create_barcode/$', views.create_barcode,name='create_barcode'),
    url(r'^create_barcode_id/(?P<id>\d+)$', views.create_barcode_id,name='create_barcode_id'),
    url(r'^barcode_generator/$', views.barcode_generator,name='barcode_generator'),
    url(r'^product_upload/$', views.product_upload,name='product_upload'),
    url(r'^create_products/$', views.create_products,name='create_products'),
    # url(r'^create_update_products/$', views.create_update_products,name='create_update_products'),
    url(r'^create_product_ajax/$', views.create_product_ajax,name='create_product_ajax'),
    url(r'^generate_code_ajax/$', views.generate_code_ajax,name='generate_code_ajax'),
    url(r'^update_product_ajax/$', views.update_product_ajax,name='update_product_ajax'),
    url(r'^product/edit_products/(?P<id>\d+)$',views.edit_products,name='edit_products'),
    url(r'^product/update_products/$',views.update_products,name='update_products'),
    url(r'^update_stock/$', views.update_stock,name='update_stock'),
    url(r'^del_products/(?P<id>\d+)$',views.del_products,name='del_products'),
    url(r'^delete_all_product/', views.delete_all_product,name='delete_all_product'),
]

reports/urls.py
from reports import views
from django.conf.urls import url

app_name='reports'
urlpatterns = [
    url(r'^create_sales_reports/$', views.create_sales_reports,name='create_sales_reports'),
    url(r'^create_monthly_reports/$', views.create_monthly_reports,name='create_monthly_reports'),
    url(r'^view_sales_reports/$', views.view_sales_reports,name='view_sales_reports'),
    url(r'^create_gst_reports/$', views.create_gst_reports,name='create_gst_reports'),
    url(r'^view_monthly_sales_reports/$', views.view_monthly_sales_reports,name='view_monthly_sales_reports'),
]

returns/urls.py
from returns import views
from django.conf.urls import url
 
app_name='returns'
urlpatterns = [
    url(r'^sales_return/$', views.sales_return,name='sales_return'),
    url(r'^create_sales_return/$', views.create_sales_return,name='create_sales_return'),
   
    url(r'^create_sales_return2/$', views.create_sales_return2,name='create_sales_return2'),
    url(r'^save_sales_return/$', views.save_sales_return,name='save_sales_return'),
    url(r'^create_sales_return_ajax/$', views.create_sales_return_ajax,name='create_sales_return_ajax'),
    url(r'^create_sales_return_ajax2/$', views.create_sales_return_ajax2,name='create_sales_return_ajax2'),
    url(r'^delete_all_return/$', views.delete_all_return,name='delete_all_return'),
   
    url(r'^returns/delete_sales_return/(?P<id>\d+)$', views.delete_sales_return,name='delete_sales_return'),
   
]

sales/urls.py
from sales import views
from django.conf.urls import url

app_name='sales'
urlpatterns = [
    url(r'^sales/$', views.sales_details,name='sales_details'),
    url(r'^sales_wholesale/$', views.sales_details_wholesale,name='sales_details_wholesale'),
    url(r'^dashboard_sales/$', views.dashboard_sales,name='dashboard_sales'),
   
    url(r'^stock_movement/$', views.stock_movement,name='stock_movement'),
    url(r'^create_sales/$', views.create_sales,name='create_sales'),
    url(r'^creating_sales/$', views.creating_sales,name='creating_sales'),
   
    url(r'^create_sales_ajax/$', views.create_sales_ajax,name='create_sales_ajax'),
    url(r'^sales/print_sales/(?P<id>\d+)$', views.print_sales,name='print_sales'),
    url(r'^sales/print_sales_wholesale/(?P<id>\d+)$', views.print_sales_wholesale,name='print_sales'),
    url(r'^sales/view_sales/(?P<id>\d+)$', views.view_sales,name='view_sales'),
   
    url(r'^sales/edit_sales/(?P<id>\d+)$', views.edit_sales,name='edit_sales'),
    url(r'^sales/update_sales/(?P<id>\d+)$', views.update_sales,name='update_sales'),
    url(r'^sales/delete_sales/(?P<id>\d+)$', views.delete_sales,name='delete_sales'),
    url(r'^sales/delete_all_sales/$', views.delete_all_sales,name='delete_all_sales'),
    url(r'^sales/delete_wholesale_sales/(?P<id>\d+)$', views.delete_wholesale_sales,name='delete_wholesale_sales'),
    url(r'^sales/delete_all_wholesale_sales/$', views.delete_all_wholesale_sales,name='delete_all_wholesale_sales'),
    url(r'^sales_dashboard_ajax/$', views.sales_dashboard_ajax,name='sales_dashboard_ajax'),
    
]

store_billing_lite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('dashboard.urls')),
    url(r'',include('product.urls')),
    url(r'',include('returns.urls')),
    url(r'',include('reports.urls')),
    url(r'',include('sales.urls')),
    url(r'',include('settings_billing.urls')),

]

dashboard/models.py
from django.db import models

# Create your models here.
class notification(models.Model):
	product_stock=models.CharField(max_length=50)
	product_low_stock_limit=models.CharField(max_length=50,blank=True)
	product_name=models.CharField(max_length=50)
	

dashboard/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect 
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from dashboard.models import notification
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

import json  
from sales.models import create_sales_table,create_sales_final,sale_totals
from product.models import products,sub_products

from returns.models import sales_returned
# Create your views here.
# def user_login(request):
# 	if request.method == 'POST':
		
# 		user_name=request.POST.get('username')
# 		pass_word=request.POST.get('password')

# 		user = authenticate(username=user_name, password=pass_word)
# 		if user:
# 			login(request,user)
# 			return HttpResponseRedirect('indexs')
# 		else:
# 			return render(request,'admin_billing/auth_login.html')
# 	return render(request,'admin_billing/auth_login.html')

def user_login(request):
	if request.method == 'POST':
		
		user_name=request.POST.get('username')
		pass_word=request.POST.get('password')


		user = authenticate(username=user_name, password=pass_word)
		if user:
			login(request,user)
			return HttpResponseRedirect('/indexs')
		else:
			return render(request,'dashboard/auth_login.html')
	return render(request,'dashboard/auth_login.html')

def user_logout(request):
	
	logout(request)
	return HttpResponseRedirect('login')


def create_table_ajax(request):
	tag_str=''
	tag_str2=''
	tag_str3=''
	tag_noti_pointer="<i class='mdi mdi-bell'></i>"
	import datetime
	now = datetime.datetime.now()
	month_31=[1,3,5,7,8,10,12]
	month_30=[4,6,9,11]

	if now.month in month_31:
		x=1
	if  now.month in month_30:
		x=2
	if(now.year%4==0 and now.year%100!=0 or now.year%400==0) and now.month==2:
		x=3
	if now.month==2:
		x=4 
	sale_tot=[]
	variablesss=[]
	for i in range(1,32):
		globals()["income_day" + str(i)] = 0
	for i in range(1,now.day+1):
		sales=sale_totals.objects.filter(sales_date__year=now.year, sales_date__month=now.month,sales_date__day=i)
		
		for s in sales:
			d=s.sales_totals
			globals()["income_day" + str(i)] = d			
	

	for i in range(1,32):
		globals()["expence_day" + str(i)] = 0
	# for i in range(1,now.day+1):
	# 	purchases=purchase_totals.objects.filter(purchase_time__year=now.year, purchase_time__month=now.month,purchase_time__day=i)
		
	# 	for s in purchases:
	# 		d=s.purchases_total
	# 		globals()["expence_day" + str(i)] = d

	sales_to=sale_totals.objects.filter(sales_date__year=now.year, sales_date__month=now.month)
	sale_sum=0
	for h in sales_to:
		sale_sum=float(sale_sum)+float(h.sales_totals)

	# purch_to=purchase_totals.objects.filter(purchase_time__year=now.year, purchase_time__month=now.month)

	purch_su=0
	# for dd in purch_to:
	# 	purch_su=float(purch_su)+float(dd.purchases_total)

	tod_sales=sale_totals.objects.values_list('sales_totals', flat=True).get(sales_date__year=now.year, sales_date__month=now.month,sales_date__day=now.day)

	# tod_purchases=purchase_totals.objects.values_list('purchases_total', flat=True).get(purchase_time__year=now.year, purchase_time__month=now.month,purchase_time__day=now.day)
	sale_c=create_sales_final.objects.filter(sales_date__year=now.year, sales_date__month=now.month,sales_date__day=now.day)
	sale_counts=0
	for cc in sale_c:
		sale_counts=sale_counts+1
	return_counts=0
	return_c=sales_returned.objects.filter(sale_return_date__year=now.year, sale_return_date__month=now.month,sale_return_date__day=now.day)
	retu_amou=0
	for cr in return_c:
		return_counts=return_counts+1
		retu_amou=float(retu_amou)+float(cr.sale_amount_return)


	sale_invoi=create_sales_final.objects.filter(sales_date__year=now.year, sales_date__month=now.month,sales_date__day=now.day)
	sal_pr_i=[]
	sal_pr_qt=[]
	for inv in sale_invoi:
		sal_pro_id=create_sales_table.objects.filter(sales_invoice_no=inv.sale_invoice_ref)
		for idd in sal_pro_id:
			sal_pr_i.append(idd.sales_product_ref_id)
			sal_pr_qt.append(idd.sales_qty)


	pro_prices=[]
	totals=0
	for pri,prqt in zip(sal_pr_i,sal_pr_qt):
		pro_pri=sub_products.objects.values_list('product_price', flat=True).get(pk=pri)
		pro_dis=sub_products.objects.values_list('product_discount', flat=True).get(pk=pri)
		pro_cost=sub_products.objects.values_list('product_cost', flat=True).get(pk=pri)
		
		pro_prices=float(pro_pri)-float(pro_dis)-float(pro_cost)
		totals=float(totals)+float(pro_prices*prqt)

	from datetime import date

	prod_inf=notification.objects.all()
	for prost in prod_inf:
		if float(prost.product_stock)<float(prost.product_low_stock_limit):
			

			tag_str=tag_str+'<a href="#"><i class="fa fa-warning text-danger"></i>Only {} item in stock of {} remaining</a>'.format(prost.product_stock,prost.product_name)
			tag_noti_pointer=" <div style='font-size: 12px; padding-left: 18px; margin: -12px; color: red;'><i class='mdi mdi-circle'></i></div><i class='mdi mdi-bell'></i>"
	sal_inf=create_sales_final.objects.all()



	
	# now = datetime.datetime.now()
	# tasks=tasks_table.objects.all()
	# for tsk in tasks:
	# 	if tsk.create_tasks_to_time>=date.today():
	# 		tsk_user=User.objects.values_list('username', flat=True).get(pk=tsk.create_tasks_staffs)
	# 		tag_str2=tag_str2+'<a href="#"><b style="font-size: 15px;">{}</b><br>From: {} To: {}<small class="pull-right"></small></a>'.format(tsk_user,tsk.create_tasks_from_time,tsk.create_tasks_to_time)


	jsona = json.dumps({'income_day1': income_day1,'income_day2': income_day2,'income_day3': income_day3,'income_day4': income_day4,'income_day5': income_day5,
		'income_day6': income_day6,'income_day7': income_day7,'income_day8': income_day8,'income_day9': income_day9,'income_day10': income_day10,
		'income_day11': income_day11,'income_day12': income_day12,'income_day13': income_day13,'income_day14': income_day14,'income_day15': income_day15,'income_day16': income_day16,
		'income_day17': income_day17,'income_day18': income_day18,'income_day19': income_day19,'income_day20': income_day20,'income_day21': income_day21,
		'income_day22': income_day22,'income_day23': income_day23,'income_day24': income_day24,'income_day25': income_day25,'income_day26': income_day26,
		'income_day27': income_day27,'income_day28': income_day28,'income_day29': income_day29,'income_day30': income_day30,'income_day31': income_day31,
		'expence_day1':expence_day1,'expence_day2':expence_day2,'expence_day3':expence_day3,'expence_day4':expence_day4,'expence_day5':expence_day5,
		'expence_day6':expence_day6,'expence_day7':expence_day7,'expence_day8':expence_day8,'expence_day9':expence_day9,'expence_day10':expence_day10,
		'expence_day11':expence_day11,'expence_day12':expence_day12,'expence_day13':expence_day13,'expence_day14':expence_day14,'expence_day15':expence_day15,
		'expence_day16':expence_day16,'expence_day17':expence_day17,'expence_day18':expence_day18,'expence_day19':expence_day19,'expence_day20':expence_day20,
		'expence_day21':expence_day21,'expence_day22':expence_day22,'expence_day23':expence_day23,'expence_day24':expence_day24,'expence_day25':expence_day25,
		'expence_day26':expence_day26,'expence_day27':expence_day27,'expence_day28':expence_day28,'expence_day29':expence_day29,'expence_day30':expence_day30,
		'expence_day31':expence_day31,'x':x,'sale_sum':sale_sum,'purch_su':purch_su,'tod_sales':round(float(tod_sales),2),'sale_counts':sale_counts,
		'return_counts':return_counts,'retu_amou':round(float(retu_amou),2),"incomes":round(float(tod_sales)-float(retu_amou),2),'totals':round(float(totals),2),'tag_str':tag_str,'tag_str2':tag_str2,'tag_str3':tag_str3,'tag_noti_pointer':tag_noti_pointer})
	return HttpResponse(jsona, content_type='application/json')



def create_table_ajaxing(request):
	import datetime
	now = datetime.datetime.now()
	

	sales_to=sale_totals.objects.filter(sales_date__year=now.year, sales_date__month=now.month)
	sale_sum=0
	for h in sales_to:
		sale_sum=float(sale_sum)+float(h.sales_totals)

	purch_to=purchase_totals.objects.filter(purchase_time__year=now.year, purchase_time__month=now.month)

	purch_su=0
	for dd in purch_to:
		purch_su=float(purch_su)+float(dd.purchases_total)
	

	
	jsona = json.dumps({'sale_sum':sale_sum,'purch_su':purch_su})
	return HttpResponse(jsona, content_type='application/json')

@login_required(login_url='/login')
def indexing(request):
	import datetime
	now = datetime.datetime.now()

	active_sidebar0=1
	sales=create_sales_final.objects.all().order_by('-id')[:5]

	
	prod_name=[]
	purcha_id=[]
	purch_id=[]
	stock=[]



	

	sales_date=sale_totals.objects.filter(sales_date__year=now.year, sales_date__month=now.month,sales_date__day=now.day)	
	if not sales_date:
		cre_sales_timings=sale_totals(
			sales_date=now,
			sales_totals=0
			)
		cre_sales_timings.save()

	
	
	return render(request,'dashboard/dash.html',{'active_sidebar0':active_sidebar0,'sales':sales})





@login_required(login_url='/login')
def error_page(request):
	return render(request,'admin_billing/error_400.html')







# # Create your views here.
def layout(request):
	return render(request,'dashboard/layout.html')
# def indexing(request):
	
	
# 	return render(request,'dashboard/dash.html')

def searching_product(request):
	if request.method == 'POST':
		
		search_result=request.POST.get('searches')
	pro_details=products.objects.filter(id__iexact=search_result)
	if not pro_details:
		pro_details=products.objects.filter(product_code__iexact=search_result)
		if not pro_details:
			pro_details=products.objects.filter(product_name__contains=search_result)
	active_sidebar1=1
	return render(request,'product/product_details.html',{'active_sidebar1':active_sidebar1,'pro_details':pro_details})

def clearall_ajax(request):
	notification.objects.all().delete()
	jsona = json.dumps({'cleared':"cleared__"})

dashboard/templates/dashboard/auth_login.html
<!DOCTYPE html>
<html lang="en">
<head>
		{% load static %}
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/logs.png' %}">

    <title>CrmX Admin - Log in </title>
  
	<!-- Bootstrap 4.0-->
	<link rel="stylesheet" href="{% static 'assets/vendor_components/bootstrap/dist/css/bootstrap.min.css' %}">
	
	<!-- Bootstrap extend-->
	<link rel="stylesheet" href="{% static 'css/bootstrap-extend.css' %}">
	
	<!-- Theme style -->
	<link rel="stylesheet" href="{% static 'css/master_style.css' %}">

	<!-- Superieur Admin skins -->
	<link rel="stylesheet" href="{% static 'css/skins/_all-skins.css' %}">	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body class="hold-transition theme-fruit bg-gradient-fruit">
	
	<div class="container h-p100">
		<div class="row align-items-center justify-content-md-center h-p100">	
			
			<div class="col-12">
				<div class="row justify-content-center no-gutters">
					<div class="col-lg-4 col-md-5 col-12">
						<div class="content-top-agile p-10">
							<h2 class="text-white">Welcome to Maxerbox</h2>
							<p class="text-white-50">Sign in to start your session</p>							
						</div>
						<div class="p-30 rounded30 box-shadowed b-2 b-dashed">
							<form action="{% url 'dashboard:login'%}" method="post" class="form-element">
								 {% csrf_token %}
								<div class="form-group">
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text bg-transparent text-white"><i class="ti-user"></i></span>
										</div>
										<input type="text" class="form-control pl-15 bg-transparent text-white plc-white" placeholder="Username" name="username">
									</div>
								</div>
								<div class="form-group">
									<div class="input-group mb-3">
										<div class="input-group-prepend">
											<span class="input-group-text  bg-transparent text-white"><i class="ti-lock"></i></span>
										</div>
										<input type="password" class="form-control pl-15 bg-transparent text-white plc-white" placeholder="Password" name="password">
									</div>
								</div>
								  <div class="row">
									
									<!-- /.col -->
									<div class="col-12 text-center">
									  <button type="submit" class="btn btn-info btn-rounded mt-10">SIGN IN</button>
									</div>
									<!-- /.col -->
								  </div>
							</form>														

							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- jQuery 3 -->
	<script src="../../assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js"></script>
	
	<!-- fullscreen -->
	<script src="../../assets/vendor_components/screenfull/screenfull.js"></script>
	
	<!-- popper -->
	<script src="../../assets/vendor_components/popper/dist/popper.min.js"></script>
	
	<!-- Bootstrap 4.0-->
	<script src="../../assets/vendor_components/bootstrap/dist/js/bootstrap.min.js"></script>

</body>
</html>

dashboard/templates/dashboard/dash.html
{%extends 'dashboard/layout.html'%}
{% load static %}
 
{%block content%}

<div class="content-wrapper">
	  <div class="container-full">
		<!-- Content Header (Page header) -->  
		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto w-p50">
					<h3 class="page-title">Dashboard</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="#"><i class="mdi mdi-home-outline"></i></a></li>
								<li class="breadcrumb-item active" aria-current="page">Control</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class="right-title w-170">
					<span class="subheader_daterange font-weight-600" id="dashboard_daterangepicker" style="padding: 10px;">
						<span class="subheader_daterange-label">
							<span class="subheader_daterange-title"></span>
							<span class="subheader_daterange-date text-primary"></span>
						</span>
						
					</span>
				</div>
			</div>
		</div>

					<div class="box-body text-center" style="display: none;">
					  <canvas id="earning" class="h-400"></canvas>
					</div>
		<!-- Main content -->
		<section class="content">
			<div class="row">
				<div class="col-xl-3 col-12">
					
						<div class="box box-body bg-danger pull-up">
							<div class="text-center">
								<h1 class="font-size-50">Product</h1>
								<h1 class="font-size-70"><a href="{% url 'product:create_products'%}" class="text-primary"><i class="mdi mdi-plus-circle-outline"></i></h1>
								<h1 class="font-size-70"><a href="{% url 'product:product_details'%}"  class="text-primary"><i class="mdi mdi-airplay"></i></a></h1>	

							</div>	

						
					</div>
				</div>
				<div class="col-xl-3 col-12">
					
						<div class="box box-body bg-warning pull-up">
							<div class="text-center">
								<h1 class="font-size-50">Sales</h1>
								<h1 class="font-size-70"><a href="{% url 'sales:create_sales'%}" class="text-info"  target="_blank"><i class="mdi mdi-plus-circle-outline"></i></a></h1>
								<h1 class="font-size-70"><a href="{% url 'sales:sales_details'%}"  class="text-info"><i class="mdi mdi-airplay"></i></a></h1>		
							</div>					
						</div>
					
				</div>
				<div class="col-xl-3 col-12">
				
						<div class="box box-body bg-success pull-up">
							<div class="text-center">
								<h1 class="font-size-50">Return</h1>
								<h1 class="font-size-70"><a href="{% url 'returns:create_sales_return'%}" class="text-warning"><i class="mdi mdi-plus-circle-outline"></i></a></h1>
								<h1 class="font-size-70"><a href="{% url 'returns:sales_return'%}"  class="text-warning"><i class="mdi mdi-airplay"></i></a></h1>		
							</div>					
						</div>
				
				</div>
				<div class="col-xl-3 col-12">
				
						<div class="box box-body bg-info pull-up">
							<div class="text-center">
								<h1 class="font-size-50">Report</h1>
								<h1 class="font-size-70"><a href="{% url 'reports:create_sales_reports'%}" class="text-danger"><i class="mdi mdi-file-chart"></i></a></h1>
								<h1 class="font-size-70"><a href="{% url 'reports:create_monthly_reports'%}" class="text-danger"><i class="fa fa-calendar"></i></a></h1>		
							</div>					
					
					</div>
				</div>
				
						<div class="col-12 col-lg-12">
				<div class="box">
				  <div class="box-header with-border">
					<h4 class="box-title">Store Status</h4>
					<ul class="box-controls pull-right">
					  <li><a class="box-btn-close" href="#"></a></li>
					  <li><a class="box-btn-slide" href="#"></a></li>	
					  <li><a class="box-btn-fullscreen" href="#"></a></li>
					</ul>
				  </div>

				  <div class="box-body">
					  <br>
					  <div class="row">
						<div class="col-12 col-lg-10">
					  		<div class="chart" id="bar-chart" style="height: 278px;"></div>
						</div>
						<div class="col-12 col-lg-2">
						  <h5 class="text-center mb-15" style="font-weight: bold;">Sales Details</h5>

						  <div class="progress-group">
							<center>Sale Count<br><br>
							<!-- <span style="><input type=" button"="" class="btn btn-success mb-5" id="sale_cou" "> -->
								<h5 class="description-header" id="sale_cou" style="font-weight:575;"></h5>
									</span>

							
						  </div>
						  <!-- /.progress-group -->
						  <div class="progress-group">
							<center>Sale Amount</span><br><br>
							<!-- <span style="><input type=" button"="" class="btn btn-success mb-5" id="sale_amou" "> -->
								<h5 class="description-header" id="sale_amou" style="font-weight:575;"></h5>
									</span>

							
						  </div>
						  <!-- /.progress-group -->
						  
						 <div class="progress-group">
							<center>Return Count</span><br><br>
							<!-- <span style="><input type=" button"="" class="btn btn-success mb-5" id="retu_cou" "> -->
								<h5 class="description-header" id="retu_cou" style="font-weight:575;"></h5>
									</span>


							
						  </div>

						  <!-- /.progress-group -->
						  <div class="progress-group">
							<center>Sale Return</span><br><br>
							<!-- <span style="><input type=" button"="" class="btn btn-success mb-5" id="retu_amo" "> -->
								<h5 class="description-header" id="retu_amo" style="font-weight:575;"></h5>
									</span>


							
						  </div>
						  
						  <!-- /.progress-group -->
						</div>
					  </div>
					  
					 <div class="row">
						
						<div class="col-6 col-md-6">
						  <div class="description-block br-1">
							<br>
							<h5 class="description-header" id="total_incos" style="font-weight:575;"></h5>
							<span class="description-text">INCOME</span>
						  </div>
						  <!-- /.description-block -->
						</div>
						
						<!-- /.col -->
						<div class="col-6 col-md-6">
						  <div class="description-block br-1">
							<br>
							<h5 class="description-header" id="profi" style="font-weight:575;"></h5>
							<span class="description-text">PROFIT</span>
						  </div>
						  <!-- /.description-block -->
						</div>
						<!-- <div class="col-6 col-md-4">
						  <div class="description-block br-1">
							<br>
							<h5 class="description-header" id="tota_inco" style="font-weight:575;"></h5>
							<span class="description-text">TOTAL INCOME</span>
						  </div>
						
						</div> -->
						
					  </div>
				  </div>
				</div>
			</div>
					<!-- /.box-body -->
				  </div>
				  <!-- /.box -->			
				</div>
</section>

{%endblock%}	